### ISSUE TITLE
Install Error - Doxyfile

### ISSUE THREAD

**Issue by ocni-dtu** [philippkraft/cmf#16]
I'm trying to install CMF on a unix machine, but when I try to install it I get the following error:

```
  Using cached cmf-1.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tnahe9m6/cmf/setup.py", line 211, in <module>
        updateversion()
      File "/tmp/pip-build-tnahe9m6/cmf/setup.py", line 82, in updateversion
        doxycode = open('Doxyfile').readlines()
    FileNotFoundError: [Errno 2] No such file or directory: 'Doxyfile'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-tnahe9m6/cmf/ 
```
I tried on different machines but I get the same error on both of them.

**Comment by philippkraft** [comment]
Somehow the Doxyfile is not part of the pypi source distribution. Will make the setup.py more tolerant, since the Doxyfile is not needed for a pypi installation, just for the API-documentation.

Workaround, install directly from Github:

    mkdir cmf
    cd cmf 
    git clone https://github.com/philippkraft/cmf.git
    python setup.py install
