### ISSUE TITLE
Handle different compiler flags for C and C++ files

### ISSUE THREAD

**Issue by philippkraft** [philippkraft/cmf#17]
Using C flags for C++ can create warnings, this is already handled in [setup.py:51-63](https://github.com/philippkraft/cmf/blob/46767075c22dc23af286c4684acd46cc9543204e/setup.py#L51-L63). However, when gcc compiles C files from the CVODE solver, no there are warnings about using C++ flags on C code, eg. -std=C++11. On macOS with CLang, this produces errors and cmf is not compiled.

**Comment by philippkraft** [comment]
[Asking StackOverflow failed](https://stackoverflow.com/q/47872981/3032680)

**Comment by bees4ever** [comment]
On my fork https://github.com/bees4ever/cmf/tree/issue_17 I merged my changes in and get a perfect build of CMF with the cpp11 standard.

**Comment by philippkraft** [comment]
Runs in Linux without any problem
