### ISSUE TITLE
cmf.SimpleTindexSnowMelt() does not scale to Cell.area

### ISSUE THREAD

**Issue by kbstn** [philippkraft/cmf#2]
With increasing size of my cmf.project.cell.area my CVodeIntegrator rises Error.

I could trace it back to the cmf.SimpleTindexSnowMelt() function. Itr seems like its not scaling properly to the cell size.

**Comment by philippkraft** [comment]
Should work with this version, @kbstn can you check and confirm the solution?

**Comment by kbstn** [comment]
thanks for the fast response, i checked and unfortunately the fix does not solve my issue.

**Comment by kbstn** [comment]
Works now. Slight scale dependency for computation time is still there, but main issue is solved.
