### ISSUE TITLE
Bracket access to solute storage

### ISSUE THREAD

**Issue by philippkraft** [philippkraft/cmf#29]
The current access to solute (here `X`) storages of water storages (here `WS`) is super ugly:

    WS.Solute(X).state

This issue proposes a nicer access like:

    WS[X].state

Additionally we can move the conc method from water storage to a property of the solute storage

    WS[X].conc

**Comment by philippkraft** [comment]
@smultsch: What do you think?

**Comment by smultsch** [comment]
For sure, the function call "WS[X].conc" is a really clean solution. But the user needs some foreknowledge, i.e. that the water storage holds a list with solutes.

**Comment by philippkraft** [comment]
The documentation of the tracer use is not so great now anyways. I guess we can simply write a tutorial about that use.

**Comment by philippkraft** [comment]
Fixed #29. Usage see test/solute_access.py and demo/adsorption.py. Old usage is still working. Other demos get translated to new usage on the go.
