### ISSUE TITLE
CMF 1.0.4 install error on Skylla

### ISSUE THREAD

**Issue by zutn** [philippkraft/cmf#3]
New CMF Version throws error on install on skylla.

[sf1962@skylla1 ~]$ pip install cmf --upgrade --user
Collecting cmf
  Using cached cmf-1.0.4.tar.gz
Building wheels for collected packages: cmf
  Running setup.py bdist_wheel for cmf ... error
  Complete output from command /cm/shared/apps/python/3.5.0/bin/python3 -u -c "i                                                                          mport setuptools, tokenize;__file__='/tmp/pip-build-1huce24n/cmf/setup.py';f=get                                                                          attr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.clo                                                                          se();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpl3rfuglopip-w                                                                          heel- --python-tag cp35:
  /cm/shared/apps/python/3.5.0/lib/python3.5/distutils/dist.py:261: UserWarning:                                                                           Unknown distribution option: 'python_requires'
    warnings.warn(msg)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.5
  creating build/lib.linux-x86_64-3.5/cmf
  copying cmf/maps.py -> build/lib.linux-x86_64-3.5/cmf
  copying cmf/fit_retention_curve.py -> build/lib.linux-x86_64-3.5/cmf
  copying cmf/__init__.py -> build/lib.linux-x86_64-3.5/cmf
  copying cmf/describe.py -> build/lib.linux-x86_64-3.5/cmf
  copying cmf/jacobian.py -> build/lib.linux-x86_64-3.5/cmf
  copying cmf/extend_project.py -> build/lib.linux-x86_64-3.5/cmf
  copying cmf/geos_shapereader.py -> build/lib.linux-x86_64-3.5/cmf
  copying cmf/soil.py -> build/lib.linux-x86_64-3.5/cmf
  copying cmf/stopwatch.py -> build/lib.linux-x86_64-3.5/cmf
  copying cmf/cell_factory.py -> build/lib.linux-x86_64-3.5/cmf
  copying cmf/cmf_core.py -> build/lib.linux-x86_64-3.5/cmf
  creating build/lib.linux-x86_64-3.5/cmf/draw
  copying cmf/draw/hillplot.py -> build/lib.linux-x86_64-3.5/cmf/draw
  copying cmf/draw/__init__.py -> build/lib.linux-x86_64-3.5/cmf/draw
  copying cmf/draw/draw_misc.py -> build/lib.linux-x86_64-3.5/cmf/draw
  copying cmf/draw/shapemap.py -> build/lib.linux-x86_64-3.5/cmf/draw
  Skipping optional fixer: buffer
  Skipping optional fixer: idioms
  Skipping optional fixer: set_literal
  Skipping optional fixer: ws_comma
  running build_ext
  building 'cmf._cmf_core' extension
  creating build/temp.linux-x86_64-3.5
  creating build/temp.linux-x86_64-3.5/cmf
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/reach
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/atmosphere
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/geometry
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/math
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/math/integrators
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/math/integrators/sundial                                                                          s_cvode
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/math/integrators/sundial                                                                          s_cvode/src
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/water
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/upslope
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/upslope/vegetation
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/upslope/Soil
  creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/upslope/connections
  gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -                                                                          Wstrict-prototypes -fPIC -Icmf/cmf_core_src/math/integrators/sundials_cvode/incl                                                                          ude -I/home/sf1962/.local/lib/python3.5/site-packages/numpy/core/include -I/cm/s                                                                          hared/apps/python/3.5.0/include/python3.5m -c cmf/cmf_core_src/cmf.cpp -o build/                                                                          temp.linux-x86_64-3.5/cmf/cmf_core_src/cmf.o -Wno-comment -Wno-reorder -Wno-unus                                                                          ed -Wno-sign-compare -ggdb -std=c++11 -fopenmp
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/Obj                                                                          C but not for C++ [enabled by default]
  gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -                                                                          Wstrict-prototypes -fPIC -Icmf/cmf_core_src/math/integrators/sundials_cvode/incl                                                                          ude -I/home/sf1962/.local/lib/python3.5/site-packages/numpy/core/include -I/cm/s                                                                          hared/apps/python/3.5.0/include/python3.5m -c cmf/cmf_core_src/project.cpp -o bu                                                                          ild/temp.linux-x86_64-3.5/cmf/cmf_core_src/project.o -Wno-comment -Wno-reorder -                                                                          Wno-unused -Wno-sign-compare -ggdb -std=c++11 -fopenmp
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/Obj                                                                          C but not for C++ [enabled by default]
  In file included from cmf/cmf_core_src/atmosphere/meteorology.h:26:0,
                   from cmf/cmf_core_src/project.h:24,
                   from cmf/cmf_core_src/project.cpp:19:
  cmf/cmf_core_src/atmosphere/../water/WaterStorage.h:22:35: fatal error: ../mat                                                                          h/statevariable.h: No such file or directory
   #include "../math/statevariable.h"
                                     ^
  compilation terminated.
  error: command 'gcc' failed with exit status 1

  ----------------------------------------
  Failed building wheel for cmf
  Running setup.py clean for cmf
Failed to build cmf
Installing collected packages: cmf
  Found existing installation: cmf 1.0.3
    Uninstalling cmf-1.0.3:
      Successfully uninstalled cmf-1.0.3
  Running setup.py install for cmf ... error
    Complete output from command /cm/shared/apps/python/3.5.0/bin/python3 -u -c                                                                           "import setuptools, tokenize;__file__='/tmp/pip-build-1huce24n/cmf/setup.py';f=g                                                                          etattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.c                                                                          lose();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-g1dnkoy7                                                                          -record/install-record.txt --single-version-externally-managed --compile --user                                                                           --prefix=:
    /cm/shared/apps/python/3.5.0/lib/python3.5/distutils/dist.py:261: UserWarnin                                                                          g: Unknown distribution option: 'python_requires'
      warnings.warn(msg)
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/cmf
    copying cmf/maps.py -> build/lib.linux-x86_64-3.5/cmf
    copying cmf/fit_retention_curve.py -> build/lib.linux-x86_64-3.5/cmf
    copying cmf/__init__.py -> build/lib.linux-x86_64-3.5/cmf
    copying cmf/describe.py -> build/lib.linux-x86_64-3.5/cmf
    copying cmf/jacobian.py -> build/lib.linux-x86_64-3.5/cmf
    copying cmf/extend_project.py -> build/lib.linux-x86_64-3.5/cmf
    copying cmf/geos_shapereader.py -> build/lib.linux-x86_64-3.5/cmf
    copying cmf/soil.py -> build/lib.linux-x86_64-3.5/cmf
    copying cmf/stopwatch.py -> build/lib.linux-x86_64-3.5/cmf
    copying cmf/cell_factory.py -> build/lib.linux-x86_64-3.5/cmf
    copying cmf/cmf_core.py -> build/lib.linux-x86_64-3.5/cmf
    creating build/lib.linux-x86_64-3.5/cmf/draw
    copying cmf/draw/hillplot.py -> build/lib.linux-x86_64-3.5/cmf/draw
    copying cmf/draw/__init__.py -> build/lib.linux-x86_64-3.5/cmf/draw
    copying cmf/draw/draw_misc.py -> build/lib.linux-x86_64-3.5/cmf/draw
    copying cmf/draw/shapemap.py -> build/lib.linux-x86_64-3.5/cmf/draw
    Skipping optional fixer: buffer
    Skipping optional fixer: idioms
    Skipping optional fixer: set_literal
    Skipping optional fixer: ws_comma
    running build_ext
    building 'cmf._cmf_core' extension
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/cmf
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/reach
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/atmosphere
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/geometry
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/math
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/math/integrators
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/math/integrators/sundi                                                                          als_cvode
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/math/integrators/sundi                                                                          als_cvode/src
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/water
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/upslope
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/upslope/vegetation
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/upslope/Soil
    creating build/temp.linux-x86_64-3.5/cmf/cmf_core_src/upslope/connections
    gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall                                                                           -Wstrict-prototypes -fPIC -Icmf/cmf_core_src/math/integrators/sundials_cvode/in                                                                          clude -I/home/sf1962/.local/lib/python3.5/site-packages/numpy/core/include -I/cm                                                                          /shared/apps/python/3.5.0/include/python3.5m -c cmf/cmf_core_src/cmf.cpp -o buil                                                                          d/temp.linux-x86_64-3.5/cmf/cmf_core_src/cmf.o -Wno-comment -Wno-reorder -Wno-un                                                                          used -Wno-sign-compare -ggdb -std=c++11 -fopenmp
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/O                                                                          bjC but not for C++ [enabled by default]
    gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall                                                                           -Wstrict-prototypes -fPIC -Icmf/cmf_core_src/math/integrators/sundials_cvode/in                                                                          clude -I/home/sf1962/.local/lib/python3.5/site-packages/numpy/core/include -I/cm                                                                          /shared/apps/python/3.5.0/include/python3.5m -c cmf/cmf_core_src/project.cpp -o                                                                           build/temp.linux-x86_64-3.5/cmf/cmf_core_src/project.o -Wno-comment -Wno-reorder                                                                           -Wno-unused -Wno-sign-compare -ggdb -std=c++11 -fopenmp
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/O                                                                          bjC but not for C++ [enabled by default]
    In file included from cmf/cmf_core_src/atmosphere/meteorology.h:26:0,
                     from cmf/cmf_core_src/project.h:24,
                     from cmf/cmf_core_src/project.cpp:19:
    cmf/cmf_core_src/atmosphere/../water/WaterStorage.h:22:35: fatal error: ../m                                                                          ath/statevariable.h: No such file or directory
     #include "../math/statevariable.h"
                                       ^
    compilation terminated.
    error: command 'gcc' failed with exit status 1

    ----------------------------------------
  Rolling back uninstall of cmf
Command "/cm/shared/apps/python/3.5.0/bin/python3 -u -c "import setuptools, toke                                                                          nize;__file__='/tmp/pip-build-1huce24n/cmf/setup.py';f=getattr(tokenize, 'open',                                                                           open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code                                                                          , __file__, 'exec'))" install --record /tmp/pip-g1dnkoy7-record/install-record.t                                                                          xt --single-version-externally-managed --compile --user --prefix=" failed with e                                                                          rror code 1 in /tmp/pip-build-1huce24n/cmf/

**Comment by philippkraft** [comment]
Old Visual Studio project renamed statevariable.h to StateVariable.h but #include uses lower case. Fixed in cd83d3338bc2e72c717e539a0005b199010fdc72 .
