### ISSUE TITLE
Error API Manning equation

### ISSUE THREAD

**Issue by smultsch** [philippkraft/cmf#30]
Hello,

seems like there is an error in the description of the Manning's equation (https://philippkraft.github.io/cmf/classcmf_1_1river_1_1_manning.html).  I think the equation should look like this:

q_manning = (1/n_manning) * (A/P)**(2/3) * (delta_z)**(1/2)*A

Maybe split the calculation of the total flow (m3/sec) into the two calculation steps flow_velocity (m/s) and flow_rate (m³/sec):

flow_velocity = (1/n_manning) * (A/P)**(2/3) * (delta_z)**(1/2)
flow_rate = flow_velocity * A

Cheers,
Sebastian

[check_manning.zip](https://github.com/philippkraft/cmf/files/1950241/check_manning.zip)

**Comment by philippkraft** [comment]
Need to check if the error is also in the calculation
