### ISSUE TITLE
error with the state variable after any(?) flux connection

### ISSUE THREAD

**Issue by richardneumann84** [philippkraft/cmf#32]
having a (1D) model setup including: 
```
A = valueA
B = valueB
cmf.external_control_connection(source, traget, A * source.volume^2 + B * source.volume)
```
 I run it by

`for t in solver.run(start, end, cmf.day):`

but it doesn't seem to work.

could you please provide an excample how to use cmf.external_control_connection

**Comment by philippkraft** [comment]
@richardneumann84, can you post here a complete, running example and the error message? From your issue I can not tell you what the problem is exactly. One problem I do spot is that you are using the binary XOR-operator `^` at a place where I would expect the power operator `**`.

Please check your example **before** posting, if it behaves as expected in a **new** interactive command line.

**Comment by richardneumann84** [comment]
Using the following code I recognize that cmf_external_control_connection does not dynamically query the actual state from every time-step - I wish it would. 
And target1.volume does not respond to the incoming flux.
```
from matplotlib import pyplot as pl
from pylab import *
import cmf as cmf
from datetime import datetime,timedelta
project = cmf.project()
cell = project.NewCell(x=0,y=0,z=0,area=1000, with_surfacewater=True) 
cell.surfacewater_as_storage()
solver = cmf.CVodeIntegrator(project,1e-7) 
solver.t = cmf.Time(1,11,2006) 
start = datetime(2006, 11, 1)
end = datetime(2007, 11, 1)

##create new storages:
target1 = project.NewStorage("target1", 0,0,0)
target2=project.NewStorage("target2", 0,0,0)
sw = cell.surfacewater
sw.volume=10000
cmf.external_control_connection(sw,target1,0.01*sw.volume** + 0.01*sw.volume)
print(target1.connections)
##what to save while run:
vol_sw=[]
vol_target1=[]
sw_target1=[]
wb_target1=[]
wb_sw=[]


for t in solver.run(start, end, cmf.day): 
    vol_sw.append(sw.volume)
    vol_target1.append(target1.volume)
    sw_target1.append(sw.flux_to(target1,t))
    wb_target1.append(target1.waterbalance(t))
    wb_sw.append(sw.waterbalance(t))
    
    
plot(vol_target1,label='volume target1')
plot(vol_sw,label='volume surfacewater')   
legend(loc='right')  
show()

plot(sw_target1,label='flux surfacewater to target1')
plot(wb_target1,label='waterbalance target1')
plot(vol_target1,label='volume target1')
legend(loc='right')
show()
```

**Comment by philippkraft** [comment]
I am still unsure, what you would like to do and what function you are expecting from the external control connection. The **external** part means, that some state / process outside of your cmf model controls your flux - it is a very special connection and is only used if you have some second model, or as written in the docs: 

> Flux from one node to another, controlled by the user or an external program, by changing the flux constant. 

A typical use case is a rule regulated dam.

From your code I guess you want to have a "normal" connection, controlled by an internal state in the form:

q = k * V**2 + k * V

I am sorry, there is until now no flow connection in that form. If you have a scientific need for that formulation or you can send me a reference where this formula has been used, I can implement your approach quite simple as a new connection in the C++ code. And it would need a name :-).

I see, that this formulation differs from the PowerLawConnection, but have you read already the [tutorial on kinematic waves](https://philippkraft.github.io/cmf/cmf_tut_kinematic_wave.html)?

For starting, I would recommend to stick to connections used in the tutorials, functionality not covered by a tutorial is always experimental.

**Comment by philippkraft** [comment]
And a 2nd issue is to create the solver before the storages - the solver contains only the statevariables given on creation.

**Comment by philippkraft** [comment]
@richardneumann84 would this [structure tutorial](file:///C:/Users/kraft-p/Documents/Code/cmf/doxy/html/cmf_tut_structure.html) have prevented you from the mistake above?
