### ISSUE TITLE
Additional (simple) way to compute Evapotransporation

### ISSUE THREAD

**Issue by zutn** [philippkraft/cmf#34]
Oudin et al (2005, Which potential evapotranspiration input for a lumped
rainfall–runoff model?) developed an simple PET calculation method. This seems to be working very good for lumped conceptual models and also needs little forcing data (Mean Temperature and Radiation).
Might be worth including.

**Comment by philippkraft** [comment]
ETpot = R_e(DOY) / (λρ)(T_a + K_2)/K_1
R_e(DOY, Latitude) = Extraterrestial radiation, as in Hargreaves
λρ = latent heat of vaporization per litre water
Jensen-Hainse (1963): K_1 = 40, K_2 = 0
McGuiness-Bordne (1972): K_1 = 68, K_2 = 5
Oudin et al (2005): K_1 = 100, K_2 = 5

**Comment by philippkraft** [comment]
# Steps to do
- [ ] Move R_e calculation to meteostation and make R_e part of Weather
- [ ] Update Hargreave - Samani to use Weather's R_e
- [ ] Implement Oudin et al ETpot with adjustable constants K_1, K_2 in ET.h
