### ISSUE TITLE
GIR of ShuttleworthWallace description

### ISSUE THREAD

**Issue by richardneumann84** [philippkraft/cmf#35]
using GIR in a simple model (attached file) with and without canopy cover results in
![grafik](https://user-images.githubusercontent.com/38858133/39800371-c5a11642-5367-11e8-8b06-abbf647e02fc.png)
and
![grafik](https://user-images.githubusercontent.com/38858133/39800385-d416a9b2-5367-11e8-8ca1-11f934db5514.png)
and
![grafik](https://user-images.githubusercontent.com/38858133/39800397-dd72de2c-5367-11e8-83fa-713e342c8eed.png)
this makes me think GIR is **potential** evaporation of an openwater like storage (cell.surfacewater) in [mm/day] is this right?
But I can't find any formula in your API Documentaion or tutorials how it is calculated.

Could you please provide a more detailed description?

[GIR_test_modell.zip](https://github.com/philippkraft/cmf/files/1986746/GIR_test_modell.zip)

**Comment by philippkraft** [comment]
You are right, GIR is the potential ground evaporation from the surface water below the sparse canopy. In BROOK90, ground evaporation rate (GER) is always stressed by the soil surface resistance rss, a function of the matrix potential. I have extended SW from BROOK90 with the GIR, the potential unstressed evaporation rate under a shading, transpiring and wind stopping canopy, GIR is GER with rss=0. Please note: The canopy in Shuttleworth Wallace might not be used as an intercepting water storage, but if cell.vegetation.CanopyClosure>0, the shading, air wetting and wind stopping function of the canopy still exists. The actual ground interception rate is calculated in the connection and is a function of the water level. I can fix the API documentation on that, but it will stay quite short.

**Comment by philippkraft** [comment]
@richardneumann84 can you please check the [API-Doc](https://philippkraft.github.io/cmf/classcmf_1_1upslope_1_1_e_t_1_1_shuttleworth_wallace.html) if this solves your issue at least partial?

**Comment by philippkraft** [comment]
Ok, after more checking I have to confess the GIR routine is not the correct way to account for evaporation from surfacewater under a canopy - as the model stands, this value is underestimated. Fixing will take place in branch i35_repair_GIR

**Comment by philippkraft** [comment]
Now GIR is removed from cmf and GER has the double role to act also for surface water
