### ISSUE TITLE
Never ending runs on Skylla (sometimes on PC as well)

### ISSUE THREAD

**Issue by zutn** [philippkraft/cmf#4]
When running models on Skylla the problem occurs, that some runs never seem to finish. This causes the jobs to be killed after their assigned runtime is over, without ever finishing. 
This has been happening when using Spotpy for calibration with the algorithms rope, MC and LHS.
Seems to be related to the beta value in kinematic waves. The smaller the value, the more runs never end. Values of beta > 0.5 do not seem to show this behaviour. 

Related to: 
[https://github.com/thouska/spotpy/issues/59](https://github.com/thouska/spotpy/issues/59)

**Comment by zutn** [comment]
Seems to be working for beta = 0.3 as well.

**Comment by zutn** [comment]
Beta <= ~ 0.2 seems to trigger the behaviour.

**Comment by philippkraft** [comment]
Low betas are really difficult for the solver and I can't think of a natural meaning of a beta below 0.5. A do not even have an idea for any beta < 1. The numerical woes of low betas need to be documented, both in the API and in the Kinematic Wave tutorial.

**Comment by philippkraft** [comment]
From http://fb09-pasig.umwelt.uni-giessen.de/cmf/wiki/CmfTutKinematicWave:
"
> A residual water content makes sense eg. for percolation in simplified models where percolation starts 
> only above field capacity, where the residual water content equals field capacity of the top soil, or it 
> can be used as the volume behind a dam. To find a justification for β is more challenging: β>1 
> describes systems, where flow is over linear slow for low storages and gets much faster for a large 
> storage. Unsaturated flow can be modelled that way, if one takes an analogy with the Brooks-Corey 
> retention curve, betas from 4 to 15 are reasonable. The standard beta for the "real" kinematic wave 
> from the Manning-Strickler equation for sheet flow in 53. If you find a real world meaning for β<1, please 
> inform the authors of cmf. However, for β<0.3 it is reported, that numerical instabilities will arise, even 
> when using the CVodeIntegrator

"
