### ISSUE TITLE
Multiprocessing -  'TypeError("can't pickle SwigPyObject objects",)'"

### ISSUE THREAD

**Issue by smultsch** [philippkraft/cmf#41]
Hello, 

I am trying to run several cmf1D cells in parallel with the Python in-build package multiprocessing. When I am using a simple example everything works quite well (see attached file). But when I am trying to run  a complex setup (not attached; the setup contains several sub-classes and input files and I like to clarify if this is a known issue before I upload the entire setup) an error is raised:

_"MaybeEncodingError: Error sending result: '<LandscapeModel.SubCatchment.SubCatchment object at 0x00000000052D4FD0>'. Reason: 'TypeError("can't pickle SwigPyObject objects",)'"

Any experience with this error? Seems to be related to the swig-wrapper.

Cheers,
Sebastian

[cmf_parallel.zip](https://github.com/philippkraft/cmf/files/2034038/cmf_parallel.zip)

**Comment by philippkraft** [comment]
It is easy to miss the issues given in [the multiprocessing programming guidelines](https://docs.python.org/3.3/library/multiprocessing.html#multiprocessing-programming), especially:

- Shared states
- Pickllebility (C++ objects are normally not pickable. Making even the rather primitive types pickleble is horrible, cf. #27)
- Explicitly pass resources to child processes

Some of these are not that bad on Linux / Unix as on Windows.

We worked hard in [spotpy](https://github.com/thouska/spotpy) to avoid these problems, please try to use that. Especially the MPI parallelization on Linux is working very well.
