### ISSUE TITLE
Import issue and runtime error with fit_retention_curve.py

### ISSUE THREAD

**Issue by DWindhorst** [philippkraft/cmf#42]
_from cmf import fit_retention_curve_
raises the follwoing error:
_AttributeError: Unknown C global variable 'VERSION'_

The scipy.optimize.fmin function tries unallowed values for the mf.VanGenuchtenMualem function and returns an RuntimeError.

Work arround excepet error and return high error for unallowed values.
_def get_error_vgm(params,pF,theta):
    try:
        vgm=cmf.VanGenuchtenMualem(1.0, *params)
        model_wetness=vgm.Wetness_pF(pF)
        err = np.sum((theta - params[0] * model_wetness )**2)
    except RuntimeError:
        err = 999999999
    return err_

**Comment by philippkraft** [comment]
What version are you using? I fixed that problem in Feb 2013 and reviewed it in Oct 2014.

Actual code reads as:
https://github.com/philippkraft/cmf/blob/1fcd70f1e8d0227468478f33ace8c26bf6a82ae8/cmf/fit_retention_curve.py#L62-L83
