### ISSUE TITLE
kinematic surface runoff

### ISSUE THREAD

**Issue by smultsch** [philippkraft/cmf#51]
Hello,

one question related to cmf.KinematicSurfaceRunoff. The description in the API says that "_**w** is the width of the shared boundary between the surface water storage and the target node_". For example, two storages are defined in the tutorial "surface runoff" (one cell and one outlet) which don't have a spatial extent, just only a location. So how is the parameter **_w_** calculated?

Cheers,
Sebastian

**Comment by philippkraft** [comment]
If the cell and the reach do not represent "real" spatial objects, w is unknown and KinematicSurfaceRunoff cannot be used. Or you must think of a value that represents your landscape well. Or, use PowerLawConnection with _&beta;_ = 5/3 instead. V0 = 1m * cell.area, Vres = puddledepth * cell.area and Q0 needs to be calibrated.

**Comment by smultsch** [comment]
Ok, sounds feasible. But I totally misunderstood the API and the related tutorial, even if everything is clearly explained. The width of the shared boundary is defined as 'w' in the equation but as 'flowwidth' in the function call which I didn't notice (so I mixed up parameters 'd' and 'flowwidth').

Nevertheless, the impact of the flowwidth is not that much. I tested the tutorial with different values between 1m and 1000m which led to a slight change of the runoff flux  (+/- 5%). A change of Ksat from 0.1 to 1.0 leads to an reduction round 
[test_runoff_simple.zip](https://github.com/philippkraft/cmf/files/2414262/test_runoff_simple.zip)
about 50%. All in all, I got the impression that the parameters Manning n, flowwidth and slope have only a minor impact on runoff generation comparing to the influence of the Ksat value of the top soil.

Maybe it could be a good idea to compile a manual with 'practical' advice when using CMF. There seem to be a lot of workflows and tricks which make the work with CMF easier, e.g. which parameters should be calibrated to get a good first impression of the water balance and which one can be adjusted to further improve reliability with a higher level of detail in further studies.

Please find attached the test script.

[test_runoff_simple.zip](https://github.com/philippkraft/cmf/files/2414264/test_runoff_simple.zip)
