### ISSUE TITLE
error using CMF

### ISSUE THREAD

**Issue by smultsch** [philippkraft/cmf#55]
Hello,

after successfully installation of cmf on windows an error occurs when import cmf which says "Module not found error : No module named cmf_core" (see attached screenshot). Any ideas how to solve this?

cmf-version: 1.4.1
Python:3.7.1
win64

Best regards,
Sebastian

![image](https://user-images.githubusercontent.com/38461180/50277925-0f27d000-0446-11e9-867e-297b2aa1233c.png)

**Comment by philippkraft** [comment]
I guess this is solved by now.
