### ISSUE TITLE
Drop the geo_shapereader module

### ISSUE THREAD

**Issue by philippkraft** [philippkraft/cmf#7]
Issue
-------

The geo_shapereader is not very smart and does not evolve. When I wrote it, there was no simple way to load shapefiles in Python - now there is: [pyshp](https://GeospatialPython/pyshp) [![PyPI](https://img.shields.io/pypi/v/pyshp.svg)](https://pypi.python.org/pypi/pyshp/)

Action needed
---------------
1. Write an cmf interface for `__geo_interface___` in cell_factory,  Related stack exchange: [How to read a shapefile in Python?](https://gis.stackexchange.com/questions/113799/how-to-read-a-shapefile-in-python)
2. Update Documentation

**Comment by philippkraft** [comment]
pyshp needs some improvements on handling records

**Comment by ocni-dtu** [comment]
Can you elaborate a little on the issues with records? I found it quite easy to work with?

**Comment by philippkraft** [comment]
Added pull request to GeospatialPython/pyshp#132
