### ISSUE TITLE
Add additional ET method with parameterized aerodynamic resistance

### ISSUE THREAD

**Issue by starboy1986** [philippkraft/cmf#74]
Hi,
I found CMF is very useful and I wish to develop an ET model with remote sensing.
My questions is how to add a new new ET algorithm with the parameterization of aerodymanic resistance? Does this need to write the ET code with C++ ?
I wondered whether the CMF can be easily coupling with other modelling approach.

**Comment by philippkraft** [comment]
First, **can you provide a reference to the method you are interested in?** I will get an idea how difficult any of the two ways to implement this might get.

# C++ implementation

Any water transporting equation (connection) that should be solved inside of a timestep needs to be implemented in C++. However, I can do the translation into C++ if you can provide me with tested Python-Code of the ET model, which suites the CMF approach (we can discuss that later). Both PenmanMonteithET and ShuttleworthWallaceET do calculate the aerodynamic resistance from other values (veg height, LAI), but if you prefer explicit setting of the aerodynamic resistance, such a model is well suited for CMF. 

# Coupling with other code

Model coupling (using Python as a glue language) was more or less the original goal for CMF.  If you want to couple cmf with an external ET model, there are several options:

1) Use a Neumann boundary at every layer, and set the flux from the layer (actual ET for that depth) to the plant by glue code using the results of your ET model, which respects drought.

2) Use TimeseriesETpot or ConstantETpot connections from every layer if you want CMF to deal with water stress. You can then provide the current total ETpot in mm/day to the connection in each time step and CMF deals with the drought stress and portioning by layer for you, as explained in the ET tutorial.

The data is exchanged in every timestep as a so called operator split.

We used an operator split for the following studies where we coupled CMF with a plant growth model (PMF) and a complex N turnover model (LandscapeDNDC):

https://doi.org/10.5194/adgeo-27-51-2010 
https://doi.org/10.1016/j.agrformet.2017.05.017 
https://doi.org/10.1016/j.envsoft.2016.12.002 
https://doi.org/10.5194/bg-11-2069-2014 
https://doi.org/10.1007/s10980-012-9772-x 
http://www.mssanz.org.au/modsim2011/B3/multsch.pdf
http://former.iemss.org/sites/iemss2012//proceedings/F3_0872_Kraft_et_al.pdf 
http://former.iemss.org/sites/iemss2012//proceedings/H2_0767_Windhorst_et_al.pdf

**Comment by philippkraft** [comment]
I will rename your issue to make more clear, what it is about.

**Comment by starboy1986** [comment]
Thank you very much for your kind suggestion.
I wish to account for the resistance parametrization of the viscous sublayer. The reference is
https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2016WR020111.
Besides, I want to solve the energy balance equation to estimate land surface temperature, as remote sensing can provide a reference to calibrate the model.
I sincere thank you for providing valuable suggestions.

**Comment by philippkraft** [comment]
This sounds super interesting but is quite some task. Hence I guess it is better first to go the coupling road and do a translation  into a "real" C++ connection much later. For the coupling the first question would be if you want to provide "just another" ETpot model (even a more complicated), or if you need to calculate vertical distribution of root water uptake and limitation by drought stress by your own. In the latter case, it would be great if you can seperate these tasks in your code. But we can discuss this via Skype, if you want, just write me an email to my work account. Btw. [Shuttleworth-Wallace](https://philippkraft.github.io/cmf/classcmf_1_1upslope_1_1_e_t_1_1_shuttleworth_wallace.html) is a direct translation of the original BROOK90 VB code, and shows a way to calculate multiple connections that depend on each other (eg. strong transpiration raises the in-canopy humidity and limits therefore ground evaporation). The code is super ugly as it follows the original code as close as possible.
