### ISSUE TITLE
Rewrite geometry support

### ISSUE THREAD

**Issue by philippkraft** [philippkraft/cmf#8]
Follow up to #7.
-------------------

With using the [`__geo_interface__`](https://gist.github.com/sgillies/2217756), the cells_from_polygons function will get a complete rewrite with API change. The callables are hard to explain and ugly to use. 
 - But how to gain that flexibility else? 
 - Or is documentation enough?

**Comment by philippkraft** [comment]
Add a field `string cmf::upslope::Cell::WKB` in cell.h that can be loaded with a OGC-WKB representation. That WKB can be used to create Shapely-Polygons on the fly. 

Creating cells and connecting cells can become two distinct jobs and cells_from_polygons would be simpler.

Challenge
----------

How to mark a std::string as a Python byte-string? swig/swig#752

**Comment by philippkraft** [comment]
Current usage for cell geometry now (if shapely is present):
```python
c.geometry = feature.shape
```
Needed: A cell creator helper function, like:
```python
def make_cell_from_polygon(project, polygon, z, id=None, with_surfacewater=True):
    c=p.NewCell(polygon.centroid.x, polygon.centroid.y, polygon.centroid.z, 
                polygon.area, with_surfaceswater)
    c.geometry = polygon
    if id is not None:
        c.Id = id
    return c
```

**Comment by philippkraft** [comment]
Use case for current API in [here](https://github.com/philippkraft/cmf/blob/d2648d1754657e0381f4df955154cc2b5d5810ae/demo/cmf3d-shapefile.py#L103-L108)

**Comment by ocni-dtu** [comment]
I have not encountered any issues, with the new make_cell_from_polygons. 

I would appreciate if you pushed the work to PyPI.
